name: odium_ai
description: "AI-ассистент для технической поддержки"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2+1
  path_provider: ^2.0.9
  gigachat_dart: ^0.1.2
  http: ^1.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/OpenSans_Condensed-SemiBold.ttf
          weight: 200

  uses-material-design: true
